### ISSUE TITLE
test-server error

### ISSUE THREAD

**Issue by scenaristeur** [YousefED/Matrix-CRDT#8]
hello, nice project, bravo !!! but running docke-compose up in the test-server folder give me 

```
synapse    | Traceback (most recent call last):
synapse    |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
synapse    |     return _run_code(code, main_globals, None,
synapse    |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
synapse    |     exec(code, run_globals)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 472, in <module>
synapse    |     main()
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 462, in main
synapse    |     hs = setup(sys.argv[1:])
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 355, in setup
synapse    |     config = HomeServerConfig.load_or_generate_config(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 697, in load_or_generate_config
synapse    |     obj.parse_config_dict(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 721, in parse_config_dict
synapse    |     self.invoke_all(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 347, in invoke_all
synapse    |     res[config_class.section] = getattr(config, func_name)(*args, **kwargs)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/config/repository.py", line 120, in read_config
synapse    |     self.media_store_path = self.ensure_directory(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 199, in ensure_directory
synapse    |     os.makedirs(dir_path, exist_ok=True)
synapse    |   File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
synapse    |     mkdir(name, mode)
synapse    | PermissionError: [Errno 13] Permission denied: '/data/media_store'
synapse exited with code 1
```

any idea ?

**Comment by scenaristeur** [comment]
there was no media_store folder
i've created it & change permissions to 777 then I got 

```
synapse    | This server is configured to use 'matrix.org' as its trusted key server via the
synapse    | 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
synapse    | server since it is long-lived, stable and trusted. However, some admins may
synapse    | wish to use another server for this purpose.
synapse    | 
synapse    | To suppress this warning and continue using 'matrix.org', admins should set
synapse    | 'suppress_key_server_warning' to 'true' in homeserver.yaml.
synapse    | --------------------------------------------------------------------------------
synapse    | Traceback (most recent call last):
synapse    |   File "/usr/local/lib/python3.8/logging/config.py", line 563, in configure
synapse    |     handler = self.configure_handler(handlers[name])
synapse    |   File "/usr/local/lib/python3.8/logging/config.py", line 744, in configure_handler
synapse    |     result = factory(**kwargs)
synapse    |   File "/usr/local/lib/python3.8/logging/handlers.py", line 200, in __init__
synapse    |     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
synapse    |   File "/usr/local/lib/python3.8/logging/handlers.py", line 55, in __init__
synapse    |     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
synapse    |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
synapse    |     StreamHandler.__init__(self, self._open())
synapse    |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
synapse    |     return open(self.baseFilename, self.mode, encoding=self.encoding)
synapse    | PermissionError: [Errno 13] Permission denied: '/data/homeserver.log'
synapse    | 
synapse    | The above exception was the direct cause of the following exception:
synapse    | 
synapse    | Traceback (most recent call last):
synapse    |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
synapse    |     return _run_code(code, main_globals, None,
synapse    |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
synapse    |     exec(code, run_globals)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 472, in <module>
synapse    |     main()
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 462, in main
synapse    |     hs = setup(sys.argv[1:])
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 389, in setup
synapse    |     synapse.config.logger.setup_logging(hs, config, use_worker_options=False)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/config/logger.py", line 342, in setup_logging
synapse    |     _setup_stdlib_logging(config, log_config_path, logBeginner=logBeginner)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/config/logger.py", line 225, in _setup_stdlib_logging
synapse    |     _load_logging_config(log_config_path)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/config/logger.py", line 301, in _load_logging_config
synapse    |     logging.config.dictConfig(log_config)
synapse    |   File "/usr/local/lib/python3.8/logging/config.py", line 808, in dictConfig
synapse    |     dictConfigClass(config).configure()
synapse    |   File "/usr/local/lib/python3.8/logging/config.py", line 570, in configure
synapse    |     raise ValueError('Unable to configure handler '
synapse    | ValueError: Unable to configure handler 'file'
```

i have chmod 777 /data/homeserver.log too and it seems better : 

```
synapse    | 2022-02-22 18:23:13,485 - synapse.storage.background_updates - 398 - INFO - background_updates-0 - Starting update batch on background update 'local_group_updates_index'
synapse    | 2022-02-22 18:23:13,488 - synapse.storage.background_updates - 595 - INFO - background_updates-0 - Adding index local_group_updates_stream_id_index to local_group_updates
synapse    | 2022-02-22 18:23:13,509 - synapse.storage.background_updates - 441 - INFO - background_updates-0 - Running background update 'local_group_updates_index'. Processed 1 items in 21ms. (total_rate=0.047619047619047616/ms, current_rate=0.047619047619047616/ms, total_updated=1, batch_size=1)
synapse    | 2022-02-22 18:23:14,513 - synapse.storage.background_updates - 398 - INFO - background_updates-0 - Starting update batch on background update 'remove_deleted_devices_from_device_inbox'
synapse    | 2022-02-22 18:23:14,522 - synapse.storage.background_updates - 441 - INFO - background_updates-0 - Running background update 'remove_deleted_devices_from_device_inbox'. Processed 1 items in 6ms. (total_rate=0.16666666666666666/ms, current_rate=0.16666666666666666/ms, total_updated=1, batch_size=1)
synapse    | 2022-02-22 18:23:15,526 - synapse.storage.background_updates - 398 - INFO - background_updates-0 - Starting update batch on background update 'event_arbitrary_relations'
synapse    | 2022-02-22 18:23:15,539 - synapse.storage.background_updates - 441 - INFO - background_updates-0 - Running background update 'event_arbitrary_relations'. Processed 0 items in 10ms. (total_rate=None/ms, current_rate=None/ms, total_updated=0, batch_size=1)
synapse    | 2022-02-22 18:23:16,542 - synapse.storage.background_updates - 398 - INFO - background_updates-0 - Starting update batch on background update 'remove_dead_devices_from_device_inbox'
synapse    | 2022-02-22 18:23:16,555 - synapse.storage.background_updates - 441 - INFO - background_updates-0 - Running background update 'remove_dead_devices_from_device_inbox'. Processed 1 items in 10ms. (total_rate=0.1/ms, current_rate=0.1/ms, total_updated=1, batch_size=1)
synapse    | 2022-02-22 18:23:16,558 - synapse.storage.background_updates - 272 - INFO - background_updates-0 - No more background updates to do. Unscheduling background update task.


```

on localhost:8888, Synapse is Running !  thxs
